apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ansible-lifecycle-driver
spec:
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: ansible-lifecycle-driver
        part-of: lm
    spec:
      hostAliases:
      {{- if .Values.app.config.kafka.hostEnabled }}
        - ip: {{ .Values.app.config.kafka.host }}
          hostnames:
          - "kafka"
      {{- end }}
      containers:
        - name: ansible-lifecycle-driver
          image: {{ .Values.docker.image }}:{{ .Values.docker.version }}
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          securityContext:
            # run as ald
            runAsUser: 100
          ports:
          - containerPort: 8293
            protocol: TCP
          envFrom:
          - configMapRef:
              name: ansible-lifecycle-driver-env
          resources:
{{ toYaml .Values.app.resources | indent 12 }}
          volumeMounts:
          - name: config
            mountPath: /var/ald/ald_config.yml
            subPath: ald_config.yml
      volumes:
      - name: config
        configMap:
          name: ansible-lifecycle-driver
