apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ansible-lifecycle-driver
spec:
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: ansible-lifecycle-driver
        part-of: lm
    spec:
      hostAliases:
      {{- if .Values.app.config.kafka.hostEnabled }}
        - ip: {{ .Values.app.config.kafka.host }}
          hostnames:
          - "kafka"
      {{- end }}
{{- if .Values.app.affinity }}
      affinity:
{{ toYaml .Values.app.affinity | indent 8 }}
{{- end }}
{{- if .Values.app.tolerations }}
      tolerations:
{{ toYaml .Values.app.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: ansible-lifecycle-driver
          image: {{ .Values.docker.image }}:{{ .Values.docker.version }}
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          securityContext:
            # run as ald
            runAsUser: 100
          ports:
          {{- if .Values.app.config.security.ssl.enabled }}
          - containerPort: 8393
            protocol: TCP
            name: https
          {{- else }}
          - containerPort: 8293
            protocol: TCP
            name: http
          {{- end }}
          envFrom:
          - configMapRef:
              name: ansible-lifecycle-driver-env
          resources:
{{ toYaml .Values.app.resources | indent 12 }}
          volumeMounts:
          - name: config
            mountPath: /var/ald/ald_config.yml
            subPath: ald_config.yml
          {{- if and .Values.app.config.security.ssl.enabled .Values.app.config.security.ssl.secret.name }}
          - name: {{ .Values.app.config.security.ssl.secret.name }}
            mountPath: /var/ald/certs
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: ansible-lifecycle-driver
      {{- if and .Values.app.config.security.ssl.enabled .Values.app.config.security.ssl.secret.name }}
      - name: {{ .Values.app.config.security.ssl.secret.name }}
        secret:
          secretName: {{ .Values.app.config.security.ssl.secret.name }}
      {{- end }}