---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- if .Values.app.config.security.ssl.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    ingress.kubernetes.io/secure-backends: "true"
  {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  {{- end }}   
    ingress.kubernetes.io/rewrite-target: /  # This line is only needed when deploying on IBM Cloud Private.
  name: ald-ingress  # The ingress name must be unique for each ingress rule created.
spec:
  rules:
  - host: {{ .Values.app.config.ingress.host }}
    http:
      paths:
      - path: /  # This is the url path used to access the service externally.
        backend:
         serviceName: ansible-lifecycle-driver
         servicePort: 8293
  {{- if .Values.app.config.security.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.app.config.security.ssl.secret.commonName }}
    secretName: {{ .Values.app.config.security.ssl.secret.name }}
  {{- end }}