apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ansible-lifecycle-driver
spec:
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: ansible-lifecycle-driver
    spec:
      hostAliases:
      {{- if .Values.app.config.kafka.hostEnabled }}
        - ip: {{ .Values.app.config.kafka.host }}
          hostnames:
          - "kafka"
      {{- end }}
      containers:
        - name: ansible-lifecycle-driver
          image: {{ .Values.docker.image }}:{{ .Values.docker.version }}
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          ports:
          - containerPort: 8293
            protocol: TCP
          envFrom:
          - configMapRef:
              name: ansible-lifecycle-driver-env
          volumeMounts:
          - name: config
            mountPath: /var/ansible-lifecycle-driver/avd_config.yml
            subPath: avd_config.yml
          - mountPath: "/var/ansible-lifecycle-driver/ald.crt"
            name: ald.crt
            readOnly: true
          - mountPath: "/var/ansible-lifecycle-driver/ald.key"
            name: ald.key
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: ansible-lifecycle-driver
      - name: ald.crt
        secret:
          secretName: ald.crt
      - name: ald.key
        secret:
          secretName: ald.key