apiVersion: v1
kind: Service
metadata:
  name: ansible-lifecycle-driver
  labels:
    app: ansible-lifecycle-driver
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8293
    targetPort: 8293
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
{{- if .Values.app.config.security.ssl.enabled }}
  - port: 8294
    targetPort: 8294
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.sslNodePort }}
{{- end }}
    protocol: TCP
    name: https
{{- end }}
  selector:
    app: ansible-lifecycle-driver
