apiVersion: v1
kind: Service
metadata:
  name: ansible-lifecycle-driver
  labels:
    app: ansible-lifecycle-driver
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8293
    targetPort: 8293
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: https
  selector:
    app: ansible-lifecycle-driver
