branches:
  only:
  - master
  - develop
language: python
python:
- '3.6'
- '3.7'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: WI3tGIXyHZQHiPhfXMDfvUtb5Yytz8HkGKNvPBU/rRvpdgfr67EvwqJLJGHWv/Qmfn/ewX+zoVv1ovcHfY9MxyiuGMfTBNlrslUh0AXLxp5L61YSKUxhBI/cDkkRLOslD5WQZ1f5jdE7X8Ym2y96RbHx11fRPjeHomcuFWQFs4TvG+oGlZcYDLa+OYbjm9grD0XbclruXRa8pF1eO9p6xksGrFor6KG8D+ZMRCXF0vFzcdkIZAcf5JbWWt2SCvoPz+K12V/RCQwMTseG+RIdVqnYAJVT/HHCUjZRGTn+pNwnN2mAIG0ij9FF/8fpaOnt110/1Tc+pe+pqJ11xDBf6jJWyYnS72DxP8JKlsvJRfurd7W9ctdVucg79xqtY+nyx26f3WWtWYaFZKRxBKwS3YEh6vxNKxvZkjLFc+yx28Fx0cVrSH2ihehWZaVPf5lq76adljT6mHVR3FNY98cFXoQLgmaZ3wPRoL2ev1CuUy30MK3SgQlmhCPlOaP296pDQp+D+IcTFYzWMhOzbkGbV7+Rn7uClV29ja/G5+OjbuxXVoezVQIkpOmtBa2v0d2616S2ZHBDzcuCwtwanC/r8vTechwphNX652mjbIl0jt5uK/j8xsHX5UhP9dDRCwxSCVXE8OVxISAzEIgl/6XkWt42f+iO/QGChGVvl7ERcBc=
