branches:
  only:
  - master
language: python
python:
- '3.8'
- '3.9'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: ErDwBqO5jtB7ARIpMM8cfwu7H8KMd0ZHpqttefQAYzkerCcmLWzFjXFmKK58eLvNGo7u0RTRTlYKXaVU50PBQLqWx7PhJvAmdmEEb1RBypkNMJ6M3hGQAEv9bqv7GnaqwV9mwLMnTDrqVZa0LOgmHqR1j6RUb38bdPEWLsGQtgtxnpsTAHT2eyBZ74BhSwiqjjLcbp44Q6kSCkLmLOlcOGb+NsSVASrH2ptalufyrnDYKOKIS43dFH8ioFcY6jMbGjh/4FbvDTBimQqdcRJYkSwOP3NDawUTOusroqvP7YJgXmE/89cwW+uXT90tL09Xzt9V2mwRmhY0z0bSOOym692AKdbjlztToJdgmds0E9cjvOcY4jQK1kesNYBMDVl/U4q63PHIWaVArBd+DmD/HlJHGRaOCiZAZtRzwrkVH2VtBVo+aW7UZ9vEhcAOWD1lYA/z9B9fUMn7anKHxanDFpRfFXoirxe1FVcHmAD6BIJFz++bmk4VMqryt6bmVTV5ddgkl4VAOBefR5e9jd3XMyrI6Iu/E1VWwxNvF9X1IirTWVD9xK2f/uodsiGx1EUbju6aMiPIqruZbXpH+RSCjiEfUe0kRA/qIH/R8zNLCuKWbgCrpc8PR1/ChcCmkIguGUGXAhEA/j7XtaFFbf/hUK5BvIPw7CGN7DfG94dQ680=
