branches:
  only:
  - master
language: python
python:
- '3.8'
- '3.9'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: HtKSJ/KB/Crj83fMhpMCD9KJJ5lnEEN8hJ4N0EfexPMtvQ1Jsc2H6o0CqAaEZBn+HW/hpRR1XO6ILH23UEJTbmOvzFnt9Gk4k5tYIOUoirL80YM7T4SG6H4K6GbihT6PtzCKXAGAHUVsBcbCAZT97OtaZdhVf2FR2IYu7KXdTXLe/CuwxUD2hGRufrAoOlZ7tvVkxvqJjMMCWh4//KL/dHK3lOns5HfXherr/yNqEwN1w4Joui3sqPQ5eXPm1ROx53zNbInH7FAFmG6ozYjylrZ1D24HfBtahD4Ch8zvp/kua+22tLWx1EWFJhH0ibzSBj1jeDVtyRIzVa+8JOA2Nujv+98GWXFFmZAz6c0itZLe7IayJDfAf1f5u5g5wsFtiC+W6jl6YJTrEbJCyKq3GsDmgeaYy4Wnb3OAi3zUTXwxrkyQBiVMepIPHryLDDQcLzxgFl7nA1/RNDITmnK9+BneQMiDVdPpVx/j5CWsoEFOGW4Gx3vfLLBj5d3fn8ZeSpVrv8mXW8dJ/xLEHu+QHayRoSUWrOO8RxPmcrMrux2HEfSWkhch8h7FimYPXWqMaIHoaFJ7lAoc9qPEmqLUPNEdUFbc9f4gc8lpci8cEwPQ0ZOTL+ykHwfiXIuJA0Id6W5uL8CHy74npbYzs0Zy9DuNK8X5SGSgUzjmRzl/cgI=
