name: ansiblelifecycledriver
version: 2.2.0.nfvi
appVersion: 2.2.0.nfvi
apiVersion: v1
description: A Helm chart for the Ansible Lifecycle Driver
keywords:
- OSS
- LM
- OSSLM
- Resource Manager
- Brent
- Ansible
- Accanto
engine: gotpl
