name: ansiblelifecycledriver
version: 0.5.1
appVersion: 0.5.1
apiVersion: v1
description: A Helm chart for the Ansible Lifecycle Driver
keywords:
- OSS
- LM
- OSSLM
- Resource Manager
- Brent
- Ansible
- Accanto
engine: gotpl
