name: ansiblelifecycledriver
version: 1.1.1.dev0
appVersion: 1.1.1.dev0
description: A Helm chart for the Ansible Lifecycle Driver
keywords:
- OSS
- LM
- OSSLM
- Resource Manager
- Brent
- Ansible
- Accanto
engine: gotpl
