---
application:
  port: 8293
  ssl:
    enabled: True
    cert_dir: /var/ald/certs

bootstrap:
  request_queue:
    enabled: True

ansible:
  unreachable_sleep_seconds: 5
  max_unreachable_retries: 60
  output_prop_prefix: 'output__'
  tmp_dir: /var/ald
  log_progress_events: True

process:
  process_pool_size: 10
  use_process_pool: True

messaging:
  connection_address: kafka:9092
  # timeout waiting for initial version check on Kafka producer/consumer initialisation
  # 5000ms is usually sufficient, increase if problems with NoBrokersAvailable occur
  api_version_auto_timeout_ms: 5000

resource_driver:
  scripts_workspace: ./lifecycle_scripts
  async_messaging_enabled: False
  keep_files: False
  lifecycle_request_queue:
    enabled: True
    group_id: ald_request_queue
    max_poll_interval_ms: 3600000
    topic:
      auto_create: True
      num_partitions: 1
      replication_factor: 1
      config:
        # 1 hour
        retention.ms: 3600000
        message.timestamp.difference.max.ms: 3600000
        file.delete.delay.ms: 3600000
    failed_topic:
      auto_create: True
      num_partitions: 1
      replication_factor: 1
