---
application:
  port: 8293
  ssl:
    enabled: True
    cert_dir: /var/ald/certs

ansible:
  unreachable_sleep_seconds: 5
  max_unreachable_retries: 60
  output_prop_prefix: 'output__'
  tmp_dir: /var/ald

process:
  process_pool_size: 50
  max_concurrent_ansible_processes: 20
  max_queue_size: 500
  use_process_pool: True
  is_threaded: False

messaging:
  connection_address: kafka:9092

lifecycle:
  scripts_workspace: ./lifecycle_scripts
  async_messaging_enabled: False
  request_queue:
    enabled: True
    group_id: request_queue_consumer
    topic:
      # name: inf_requests
      auto_create: True
      num_partitions: 20
      replication_factor: 1
      config:
        # 1 day
        retention.ms: 86400000
        message.timestamp.difference.max.ms: 86400000
        file.delete.delay.ms: 86400000
  keep_scripts: False
  async_messaging_enabled: False

