---
application:
  port: 8293
  ssl:
    enabled: True
    cert_dir: /var/ald/certs

ansible:
  unreachable_sleep_seconds: 5
  max_unreachable_retries: 1000
  output_prop_prefix: 'output__'

process:
  process_pool_size: 10
  max_concurrenty_ansible_processes: 10
  max_queue_size: 100
  use_pool: True
  is_threaded: False

messaging:
  connection_address: kafka:9092

lifecycle:
  scripts_workspace: ./lifecycle_scripts
  keep_scripts: False
  async_messaging_enabled: False